services:
  app:
    build:
      context: .
    ports:
      - 5173:5173
      - 4173:4173
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    command: sleep infinity

volumes:
  node_modules:
